### ISSUE TITLE
feat(course/progress): add progress tracking for a course 

### ISSUE THREAD

**Issue by robinboehm** [audioslides/audioslides.io#7]
Show progress for course and lesson.
First implementation should be only a simple value that is defined via edit.
Next steps: track technical tasks like SEO, title length, ...

Example:
<img width="713" alt="screen shot 2017-11-29 at 14 29 52" src="https://user-images.githubusercontent.com/820391/33377443-ca8c412e-d511-11e7-8724-7c68c9fed4c1.png">

**Comment by sbrink** [comment]
<img width="256" alt="screen shot 2017-12-07 at 11 09 14" src="https://user-images.githubusercontent.com/55469/33709865-15b7e170-db3f-11e7-8bc7-db2e80fcd5f4.png">

**Comment by sbrink** [comment]
Added only helpers for displaying the percentages.
